---
title: ""
---

<p><font size="4">**The Randomizer:**<br>
*A tool to foster participation and reduce instructors' unconscious biases*</font></p>

Part of my teaching philosophy is to foster a learning environment where students actively participate in class. I am particularly interested in strategies that address instructors' unconscious biases. With that goal in mind, I programmed "The Randomizer," an R function designed to assist instructors in incentivizing and grading participation. "The Randomizer" randomly selects students to participate, thereby creating the opportunity for students that would otherwise not express their opinions to do so (and to gain confidence in the process). It provides a clear and transparent way to create engagement while eliminating the practical difficulties instructors face in registering participation points. 

The inspiration for "The Randomizer" came from one of Professor Guy Whitten's courses. He created the very first randomizer, a Stata do-file with which he would invite students to answer questions in class. "The Randomizer" advances the do-file by i) solving all the practical difficulties of keeping track of participation points and ii) by incorporating students' participation history to create conditional probabilities. Among the function's many features, it automatically creates a CSV file with students' participation and grades throughout the semester, prioritizes students who participated the least when creating the draws (particularly helpful in large classrooms), and allows instructors to easily account for students on temporary leave (so common during pandemic times).


The Randomizer function and complete documentation are available <a href="https://github.com/andrea-junqueira/TheRandomizer" target="_blank">here.</a>