---
title: ""
---

<font size="6"> **Teaching**</font>

<br /> 

<font size="4"> ***Instructor of Record*** </font>

<p>POLS 323: Political Systems of Latin America<br>
Undergraduate level<br>
Texas A&M University<br>
Fall 2021 and Spring 2022<br>
<a href="./survey_results_aggregate_20220103_1632.pdf" target="_blank">Evaluations Fall 2021 (PDF)</a> <br>
<a href="./survey_results_aggregate_20220823_1014.pdf" target="_blank">Evaluations Spring 2022 (PDF)</a> </p>

<br /> 

<font size="4"> ***Teaching Assistant (Graduate Level)*** </font>

<p>POLS 621: Theory and Method in Comparative Politics<br>
Texas A&M University<br>
Professor: Florian Hollenbach<br>
Fall 2020</p>

<p>POLS 602: Quantitative Political Analysis<br>
Texas A&M University<br>
Professor: Paul Kellstedt<br>
Fall 2019</p>

<p>FLP 0406: Quantitative Research in Political Science<br>
University of São Paulo<br>
Professor: Glauco Peres<br>
Spring 2016</p>

<br /> 

<font size="4"> ***Teaching Assistant (Undergraduate Level)*** </font>

<p>POLS 209: Introduction to Political Science Research<br>
Texas A&M University<br>
Professor: Dominique Lewis<br>
Spring 2019</p>

<br /> 

<font size="4"> ***Teaching Assistant (International Political Science Association IPSA Summer School)*** </font>

<p>Modern Regression Analysis<br>
IPSA Summer School - Singapore<br>
Professors: Guy Whitten and Katsunori Seki<br>
July 2020</p>

<p>Causal Inference and Field Experiments<br>
IPSA Summer School - São Paulo<br>
Professor: Florian Foos<br>
July 2020</p>

